resources:
  PrestaShop\PrestaShop\Core\Domain\Hook\QueryResult\HookStatus:
    operations:
      ApiPlatform\Metadata\Get:
        provider: PrestaShopBundle\Api\Provider\QueryProvider
        extraProperties:
          query: PrestaShop\PrestaShop\Core\Domain\Hook\Query\GetHookStatus
        uriTemplate: '/hook-status/{id}'
        requirements:
          id: '\d+'
        exceptionToStatus:
          PrestaShop\PrestaShop\Core\Domain\Hook\Exception\HookNotFoundException: 404
