services:
  _defaults:
    public: false
    autowire: true
    autoconfigure: true
    bind:
      $multistoreFeature: '@prestashop.adapter.feature.multistore'
      $defaultCurrencyId: '@=service("prestashop.adapter.legacy.configuration").get("PS_CURRENCY_DEFAULT")'
      $formRenderer: '@twig.form.renderer'
      $multistoreCheckboxEnabler: '@prestashop.multistore_checkbox_enabler'
      $flashBag: '@session.flash_bag'
      $addDisablingSwitchListener: '@form.event_listener.add_disabling_switch_listener'

  PrestaShopBundle\Form\Admin\Extension\:
    resource: "../../../../../Form/Admin/Extension/*"

  PrestaShopBundle\Form\Extension\:
    resource: "../../../../../Form/Extension/*"

  form.extension.comma_transformer:
    alias: 'PrestaShopBundle\Form\Admin\Extension\CommaTransformerExtension'
    deprecated: ~
    public: true
  form.type.extension.money:
    alias: 'PrestaShopBundle\Form\Admin\Extension\CustomMoneyTypeExtension'
    deprecated: ~
    public: true
  form.type.extension.resizable_text:
    alias: 'PrestaShopBundle\Form\Extension\ResizableTextTypeExtension'
    deprecated: ~
    public: true
  form.extension.help_text:
    alias: 'PrestaShopBundle\Form\Admin\Extension\HelpTextExtension'
    deprecated: ~
    public: true
  form.extension.hint_text:
    alias: 'PrestaShopBundle\Form\Admin\Extension\HintTextExtension'
    deprecated: ~
    public: true
  form.extension.default_empty_data:
    alias: 'PrestaShopBundle\Form\Admin\Extension\DefaultEmptyDataExtension'
    deprecated: ~
    public: true
  form.extension.data_list:
    alias: 'PrestaShopBundle\Form\Extension\DataListExtension'
    deprecated: ~
    public: true
  form.extension.row_attributes:
    alias: 'PrestaShopBundle\Form\Admin\Extension\RowAttributesExtension'
    deprecated: ~
    public: true
  form.extension.external_link:
    alias: 'PrestaShopBundle\Form\Admin\Extension\ExternalLinkExtension'
    deprecated: ~
    public: true
  form.extension.alert:
    alias: 'PrestaShopBundle\Form\Admin\Extension\AlertExtension'
    deprecated: ~
    public: true
  form.extension.label_options:
    alias: 'PrestaShopBundle\Form\Admin\Extension\LabelOptionsExtension'
    deprecated: ~
    public: true
  form.extension.form_theme:
    alias: 'PrestaShopBundle\Form\Admin\Extension\FormThemeExtension'
    deprecated: ~
    public: true
  form.extension.columns_number:
    alias: 'PrestaShopBundle\Form\Admin\Extension\ColumnsNumberExtension'
    deprecated: ~
    public: true
  form.extension.multistore_configuration:
    alias: 'PrestaShopBundle\Form\Admin\Extension\MultistoreConfigurationTypeExtension'
    deprecated: ~
    public: true
  form.extension.unit:
    alias: 'PrestaShopBundle\Form\Admin\Extension\UnitTypeExtension'
    deprecated: ~
    public: true
  form.extension.multistore_dropdown:
    alias: 'PrestaShopBundle\Form\Admin\Extension\MultistoreExtension'
    deprecated: ~
    public: true
  form.extension.downloadable_file:
    alias: 'PrestaShopBundle\Form\Admin\Extension\DownloadFileExtension'
    deprecated: ~
    public: true
  form.extension.alerts_tracking_extension:
    alias: 'PrestaShopBundle\Form\Admin\Extension\AlertsTrackingExtension'
    deprecated: ~
    public: true
  form.extension.modify_all_shops_extension:
    alias: 'PrestaShopBundle\Form\Admin\Extension\ModifyAllShopsExtension'
    deprecated: ~
    public: true
  form.extension.disabling_switch_extension:
    alias: 'PrestaShopBundle\Form\Admin\Extension\DisablingSwitchExtension'
    deprecated: ~
    public: true

  prestashop.multistore_checkbox_enabler:
    class: PrestaShopBundle\Service\Form\MultistoreCheckboxEnabler
    arguments:
      - '@prestashop.adapter.feature.multistore'
      - '@prestashop.adapter.legacy.configuration'
      - '@prestashop.adapter.shop.context'
      - '@prestashop.core.admin.multistore'
      - '@PrestaShopBundle\Form\FormCloner'
