services:
  prestashop.bundle.form.admin.improve.design.theme.page_layout_customization_form_factory:
    alias: 'PrestaShopBundle\Form\Admin\Improve\Design\Theme\PageLayoutCustomizationFormFactory'
    deprecated: ~
    public: true
