services:
  form.form_cloner:
    alias: PrestaShopBundle\Form\FormCloner
    deprecated: ~
    public: true

  form.form_builder_modifier:
    alias: PrestaShopBundle\Form\FormBuilderModifier
    deprecated: ~
    public: true

  prestashop.multistore_checkbox_enabler:
    alias: 'PrestaShopBundle\Service\Form\MultistoreCheckboxEnabler'
    deprecated: ~
    public: true
