services:
  _defaults:
    public: false

  PrestaShopBundle\Form\FormCloner:

  form.form_cloner:
    alias: PrestaShopBundle\Form\FormCloner
    public: true
    deprecated: ~

  form.form_builder_modifier:
    class: PrestaShopBundle\Form\FormBuilderModifier
    public: true

  PrestaShopBundle\Service\Form\MultistoreCheckboxEnabler:
    arguments:
      - '@prestashop.adapter.feature.multistore'
      - '@prestashop.adapter.legacy.configuration'
      - '@prestashop.adapter.shop.context'
      - '@prestashop.core.admin.multistore'
      - '@form.form_cloner'

  prestashop.multistore_checkbox_enabler:
    alias: 'PrestaShopBundle\Service\Form\MultistoreCheckboxEnabler'
    deprecated: ~
    public: true
