admin_shops_search:
  path: /search/{searchTerm}
  methods: [ GET ]
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\Configure\AdvancedParameters\ShopController::searchAction'
    _legacy_controller: AdminAdvancedParameters
  options:
    expose: true
