# @TODO uncomment legacy links when page is done
admin_search_index:
  path: /
  methods: [ GET ]
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\Configure\ShopParameters\SearchController::indexAction'
    _legacy_controller: AdminSearchConf
    # _legacy_link: AdminSearchConf
    # _legacy_feature_flag: search

admin_contacts_search:
  path: /
  methods: [ POST ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\CommonController::searchGridAction
    gridDefinitionFactoryServiceId: prestashop.core.grid.definition.factory.contacts
    redirectRoute: admin_search_index
    _legacy_controller: AdminSearchConf
#    _legacy_link: AdminSearchConf:submitFiltercontact


admin_alias_delete_bulk:
  path: /delete/bulk
  methods: [ POST ]
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\Configure\ShopParameters\SearchController::deleteBulkAction'
    _legacy_controller: AdminSearchConf
    # _legacy_link: AdminSearchConf:submitBulkdeletealias
