admin_search:
  path: /
  methods: [ GET ]
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\Configure\ShopParameters\SearchController::indexAction'
    _legacy_controller: AdminSearchConf
    _legacy_link: AdminSearchConf
#    _legacy_feature_flag: search
