services:
  _defaults:
    public: false
    autowire: true

  PrestaShopBundle\Form\Admin\Configure\AdvancedParameters\Webservice\WebserviceKeyType:
    arguments:
      $isMultistoreFeatureUsed: '@=service("prestashop.adapter.multistore_feature").isUsed()'
      $resourceChoices: '@=service("prestashop.adapter.form.choice_provider.resources_choice_provider").getChoices()'
      $permissionChoices: '@=service("prestashop.core.form.choice_provider.permissions_choice_provider").getChoices()'
