admin_feature_get_feature_values:
  path: /{idFeature}
  methods: [ GET ]
  defaults:
    idFeature: 0
    _controller: PrestaShopBundle\Controller\Admin\FeatureController::getFeatureValuesAction
    _legacy_controller: AdminFeatures
  requirements:
    idFeature: \d+
  options:
    expose: true
