services:
  _defaults:
    public: true

  PrestaShop\PrestaShop\Core\Category\NameBuilder\CategoryDisplayNameBuilder:
    arguments:
      - '@PrestaShop\PrestaShop\Adapter\Category\Repository\CategoryRepository'
      - ' > '

  prestashop.core.category.name_builder.category_display_name_builder:
    alias: PrestaShop\PrestaShop\Core\Category\NameBuilder\CategoryDisplayNameBuilder
    deprecated: ~

  PrestaShop\PrestaShop\Core\Category\Provider\MenuThumbnailAvailableKeyProvider:
    - !php/const _PS_CAT_IMG_DIR_
