services:
  _defaults:
    public: false

  PrestaShop\PrestaShop\Adapter\Admin\PagePreference:
    arguments:
      - "@session"
      - !php/const _PS_MODE_DEV_
    decorates: prestashop.core.admin.page_preference_interface

  prestashop.adapter.admin.page_preference:
    alias: PrestaShop\PrestaShop\Adapter\Admin\PagePreference
    deprecated: ~
    public: false

  prestashop.adapter.legacy_db:
    class: 'Db'
    factory: [ 'Db', 'getInstance' ]
    deprecated: '%service_id% service is deprecated and will be removed in 8.0.'
