imports:
  - { resource: alias/*.yml }

services:
  _defaults:
    public: true

  PrestaShop\PrestaShop\Adapter\Alias\Validate\AliasValidator:
    autowire: true
    public: false

  PrestaShop\PrestaShop\Adapter\Alias\Repository\AliasRepository:
    autowire: true
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'
      - '@PrestaShop\PrestaShop\Adapter\Alias\Validate\AliasValidator'


  PrestaShop\PrestaShop\Adapter\Alias\CommandHandler\AddAliasCommandHandler:
    autowire: true
    public: false
    tags:
      - name: tactician.handler
        command: PrestaShop\PrestaShop\Core\Domain\Alias\Command\AddAliasCommand
