services:
  _defaults:
    public: true

  PrestaShop\PrestaShop\Adapter\Alias\Validate\AliasValidator:
    autowire: true
    public: false

  PrestaShop\PrestaShop\Adapter\Alias\Repository\AliasRepository:
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'
      - '@PrestaShop\PrestaShop\Adapter\Alias\Validate\AliasValidator'


  PrestaShop\PrestaShop\Adapter\Alias\CommandHandler\AddAliasHandler:
    autowire: true
    public: false
    tags:
      - name: tactician.handler
        command: PrestaShop\PrestaShop\Core\Domain\Alias\Command\AddAliasCommand
    arguments:
      [ '@PrestaShop\PrestaShop\Adapter\Alias\Repository\AliasRepository' ]

  PrestaShop\PrestaShop\Adapter\Alias\QueryHandler\GetAliasForEditingHandler:
    autowire: true
    public: false
    tags:
      - name: tactician.handler
        command: PrestaShop\PrestaShop\Core\Domain\Alias\Query\GetAliasForEditing
    arguments:
      [ '@PrestaShop\PrestaShop\Adapter\Alias\Repository\AliasRepository' ]
