services:
  _defaults:
    public: false
    autowire: true

  PrestaShop\PrestaShop\Adapter\Backup\DatabaseBackupCreator:
  PrestaShop\PrestaShop\Adapter\Backup\BackupRepository:
  PrestaShop\PrestaShop\Adapter\Backup\BackupRemover:

  prestashop.adapter.backup.database_creator:
    alias: 'PrestaShop\PrestaShop\Adapter\Backup\DatabaseBackupCreator'
    public: false
    deprecated: ~

  prestashop.adapter.backup.backup_provider:
    alias: 'PrestaShop\PrestaShop\Adapter\Backup\BackupRepository'
    public: false
    deprecated: ~

  prestashop.adapter.backup.backup_remover:
    alias: 'PrestaShop\PrestaShop\Adapter\Backup\BackupRemover'
    public: false
    deprecated: ~
